import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.scss'

import Navbar from "../components/template/Navbar";
import Banner from "../components/template/Banner";
import Logo from "../components/template/Logo";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/Projects/nextjs/alurageek/public/favicon.ico" />
        </Head>

        <Navbar />

        <main>
            <Banner></Banner>
            <div>
                <div className={`conteineTitulo`}>
                    <h3>Título de seção</h3>
                    <button>Ver mais</button>
                </div>
                <div className={`conteinerProdutos`}>
                    <div className={`cardProduto`}>
                        <img src="" alt=""/>
                        <div className={`containerInfoProduto`}>
                            <span>Nome do Produto</span>
                            <span>R$ 10,20</span>
                            <button>Ver produto</button>
                        </div>
                    </div>
                    <div className={`cardProduto`}>
                        <img src="" alt=""/>
                        <div className={`containerInfoProduto`}>
                            <span>Nome do Produto</span>
                            <span>R$ 10,20</span>
                            <button>Ver produto</button>
                        </div>
                    </div>
                    <div className={`cardProduto`}>
                        <img src="" alt=""/>
                        <div className={`containerInfoProduto`}>
                            <span>Nome do Produto</span>
                            <span>R$ 10,20</span>
                            <button>Ver produto</button>
                        </div>
                    </div>
                    <div className={`cardProduto`}>
                        <img src="" alt=""/>
                        <div className={`containerInfoProduto`}>
                            <span>Nome do Produto</span>
                            <span>R$ 10,20</span>
                            <button>Ver produto</button>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <footer>
            <nav>
                <Logo />
                <ul>
                    <li>
                        <Link href="#"  >
                            <a>Quem somos nós</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="#"  >
                            <a>Política de privacidade</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="#"  >
                            <a>Programa fidelidade</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="#"  >
                            <a>Nossas lojas</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="#"  >
                            <a>Quero ser franqueado</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="#"  >
                            <a>Anuncie aqui</a>
                        </Link>
                    </li>
                </ul>
            </nav>
            <form action="">
                <label htmlFor="first">Nome:</label>
                <input type="text" id="first" name="first"/>
                <label  htmlFor="last">Escreva sua mensagem:</label>
                <input type="text" id="last" name="last"/>
                <button type="submit">Submit</button>
            </form>
            <article>
                <span>Desenvolvido por Eduardo de Moraes</span>
                <span>2022</span>
            </article>
        </footer>


    </div>
  )
}

export default Home
