import Head from "next/head";
import Navbar from "../components/template/Navbar";
import Inputitem from "../components/template/Inputitem";
import Footer from "../components/template/Footer";

export default function Login() {
    return(
        <div className={``}>
            <Head>
                <title>AluraGeek</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Projects/nextjs/alurageek/public/favicon.ico" />
            </Head>

            <Navbar />

            <main className={`flex flex-col flex-1 min-h-screen justify-center items-center bg-claro-200`}>
                <form action="" className={`container mx-auto max-w-[275px] lg:max-w-[423px] px-4 py-24`}>
                    <div className={`flex flex-col gap-4 text-center`}>
                        <span className={`text-base font-bold text-escuro-200`}>Iniciar Sessão</span>
                        <Inputitem tipo={`email`} idName={`email`} label={`Escreva seu email:`} />
                        <Inputitem tipo={`password`} idName={`password`} label={`Escreva sua senha:`} />
                        <div className={`flex flex-col items-center`}>
                            <button className={
                                `w-fit text-claro-100 bg-primary-400
                                font-semibold py-3 px-4 hover:bg-opacity-70
                                duration-200 lg:p-4 lg:font-normal`
                            } type="submit">Entrar</button>
                        </div>

                    </div>

                </form>
            </main>

            <div className={`bg-primary-100`}>
                <Footer />
            </div>

            <div className={`flex flex-col items-center bg-claro-100 px-4 md:px-8 py-4`}>
                <span>Desenvolvido por Eduardo de Moraes</span>
                <span>2022</span>
            </div>
        </div>
    )
}