import Layout from "../components/template/Layout";
import FormNovoProduto from "../components/organisms/FormNovoProduto";
import Head from "next/head";

export default function Novoproduto() {
    return(
        <div className={`bg-claro-200`}>

            <Head>
                <title>Cadastrar Produto</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Projects/nextjs/alurageek/public/favicon.ico" />
            </Head>

            <Layout>
                <div className={'flex items-center min-h-[50vh]'}>
                    <FormNovoProduto />
                </div>
            </Layout>
        </div>

    )
}